### ISSUE TITLE
Port issue between compose and settings file (misconfiguration)

### ISSUE THREAD

**Issue by DenysZvenyhorodskyi** [K4rian/docker-mednafen-server#1]
Hello,
in the compose the external and internal ports are [4060](https://github.com/K4rian/docker-mednafen-server/blob/main/compose/docker-compose.yml#L13):

```
    ports:
      - 4060:4060/tcp
```

but in the env file, it is set to   ##[4046](https://github.com/K4rian/docker-mednafen-server/blob/main/compose/mednafen-server.env#L3C1-L4C1):
```
MDFNSV_PORT=4046
```

**Comment by K4rian** [comment]
Hey,

Thanks for the report; it was indeed a mistake.
The issue was fixed in 19af2e2.
