### ISSUE TITLE
Help with build

### ISSUE THREAD

**Issue by ThiagoProg37** [K4rian/docker-mednafen-server#2]
Hello!
Sorry to use this space, but could you answer two questions for me?

I have a machine on AWS with Ubuntu and I would like to have a dedicated mednaffen server on it. 

With your server project, is this possible?

If it's possible, if I run the container on Docker and everything works, how will I know the name or address of my host server in mednaffen so that people can connect, will it be something like the server "netplay.fobby.net"?

Thank you for your attention and congratulations on the project.

**Comment by K4rian** [comment]
Hey,

> I have a machine on AWS with Ubuntu and I would like to have a dedicated Mednafen server on it.
> With your server project, is this possible?

That's the point of Docker: to deploy a container whenever you want, even on your own PC. So, yes, sure.

> If it's possible, if I run the container on Docker and everything works, how will I know the name or address of my host server in Mednafen so that people can connect? Will it be something like the server "netplay.fobby.net"?

Your AWS instance should have one (or more) public IP addresses. 

By default, the deployed Mednafen Server is reachable on port 4046, so your game server would be available at `<YOUR_INSTANCE_IP>:4046`

If you prefer a domain name (like `netplay.fobby.net`), you'll need to own one and modify the DNS entries to point to your instance's IP. `<YOUR_INSTANCE_IP>:4046` could become `netplay.thiagoprog37.com` if you want to keep `netplay` as the subdomain for your Mednafen Server.

And don't forget to open the port through your AWS panel (4046 TCP by default), or your server won't be reachable.
If you plan to make your gameserver public, consider applying some firewall rules (IP access limits, country filtering, ...) to protect your instance.

There are plenty of resources online if you're unfamiliar with these processes.

Hope this helps!

**Comment by ThiagoProg37** [comment]
@K4rian 

Hello!
Thanks for the guidance. It worked correctly, without much work.

Taking advantage, I noticed a lot of lag (both for me and for the other connected player) even though the server was from a machine very close to us, whereas, when connecting to the "emuparadise" server, there was no lag, just input delay.

That said, do the default settings of the created server influence lag? Is there anything that can be done to improve the experience?

Once again, thank you very much for all your attention.

**Comment by K4rian** [comment]
@ThiagoProg37 

Hey,

Connectivity between the client(s) and the server depends on several factors:

* Connection Quality: Inspect the latency (ping times) between each client and the server (client1→server, client2→server).
* Emulator Choice: Older systems often require less bandwidth (NES, MasterSystem, etc.)
* Game Type: Pixel-perfect platformers or fighting games are more sensitive to latency, as they require low delays to remain enjoyable.

And yes, the settings could influence connectivity. 
For example, the Mednafen authors recommend the following settings for the NES:
```
maxcmdpayload 200000  
minsendqsize  262144  
maxsendqsize  262144  
```

Feel free to experiment or ask on the official [Mednafen forums](https://forum.fobby.net/) if you need additional information.

Hope this helps. Good luck!
